name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: 
          - cypress/base:14
          - cypress/base:15
        # You can add more container versions for parallelization

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14' # Specify the node version you need

      - name: Install dependencies
        run: npm ci

      - name: Start the application
        run: npm start &

      - name: Wait for application to be available
        run: npx wait-on http://localhost:3000

      - name: Run Cypress tests
        run: npx cypress run --headless
