name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run-folder1:
    runs-on: ubuntu-latest
    container: cypress/base:14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Wait for Test Server
        run: npx wait-on https://employer-test.fastjobs.my/site/login 

      - name: Run Cypress tests for MY
        run: npx cypress run --headless --spec 'cypress/e2e/MY/**/*.js'

      - name: Generate Allure report
        run: |
          npm install -g allure-commandline --save-dev
          allure generate --clean
          allure open

      - name: Publish Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  cypress-run-folder2:
    runs-on: ubuntu-latest
    container: cypress/base:14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '15'

      - name: Install dependencies
        run: npm ci

      - name: Wait for Test Server
        run: npx wait-on https://employer-test.fastjobs.sg/ 

      - name: Run Cypress tests for SG
        run: npx cypress run --headless --spec 'cypress/e2e/SG/**/*.js'

      - name: Generate Allure report
        run: |
          npm install -g allure-commandline --save-dev
          allure generate --clean
          allure open

      - name: Publish Allure report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
